image: Visual Studio 2017

build:
  project: bittwist

after_build:
  - 7z a JavaToCSharpGui.zip %APPVEYOR_BUILD_FOLDER%\bittwistWindows\bin\Debug\*.*

artifacts:  # Archive the generated packages in the ci.appveyor.com build report.  - path: bin\Debug\*
  - path: bittwistWindows.zip
    name: artifacts-all

