image: Visual Studio 2019


environment:

  matrix:
  - TARGET: x86_64-pc-windows-msvc
    WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/x64/Packet.lib"
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
  - TARGET: i686-pc-windows-msvc
    WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/Packet.lib"
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"


install:
 - ps: mkdir C:/dl
 - curl -o "C:/dl/wpd.zip" "https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip"
 - ps: Add-Type -AssemblyName system.io.compression.filesystem
 - ps: "[io.compression.zipfile]::ExtractToDirectory(\"C:/dl/wpd.zip\", \"C:/dl/wpdpack\")"
 - ps: mkdir ${env:APPVEYOR_BUILD_FOLDER}/lib
 - ps: cp ${env:WPD_LIB_PATH} ${env:APPVEYOR_BUILD_FOLDER}/lib
 - CALL "%VCVARS%"
 - SET VCTargetsPath="C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140"
 - choco install winpcap


build:
  project: bittwist.vcxproj


after_build:
  - 7z a bittwistWindows.zip %APPVEYOR_BUILD_FOLDER%\bittwistWindows\bin\Debug\*.*

artifacts:  # Archive the generated packages in the ci.appveyor.com build report.  - path: bin\Debug\*
  - path: bittwistWindows.zip
    name: artifacts-all

